### PR TITLE
Allow user to register non standard HTTP method

### PR DESCRIPTION
**Pull request by Spy-Seth**
This PR expose the `_register` method on the server router to allow user to register custom HTTP method:

```js
router.register('PATCH', '/totos/:todoId', ({ params }, res) =>
  res.json({ id: params.todoId }),
);
```

My use case is that I want to mock some `PATCH` HTTP request. `PATCH` is not a standard HTTP but is commonly used. An RFC as been proposed for it: https://tools.ietf.org/html/rfc5789. 

If you are ok with this PR I will add some documentation before the merge

### CODE REVIEW

**Comment by idiotWu** [comment]
Hmm... Actually I don't like to expose the private methods. Can we just add `router.patch` method in respect to RFC5789?

**Comment by VincentBel** [comment]
I think `PATCH` is also a standard method, we should support it by default.

As for custom method(e.g. `PROPPATCH` `MOVE `), as [this article](https://www.safaribooksonline.com/library/view/restful-web-services/9780596809140/ch01s12.html) point out, it is not encouraged.  But adding support may better since people can use it anyway...

**Comment by Spy-Seth** [comment]
> Can we just add router.patch method in respect to RFC5789?

As it's only a proposal an not a validated RFC I was scary that you do not want it ^^ 

I will change my commit to simplify and add a `patch` method

**Comment by idiotWu** [comment]
CircleCI keeps failing because of the unexposed environment variables 😓. I will send a PR to fix that soon.

Sorry for the inconvenience.

**Comment by Spy-Seth** [comment]
> Don't forget to update typings at `typings/` directory :)

Oups! Fixed 😄

**Comment by idiotWu** [comment]
@Spy-Seth and typing tests at `typings/test/server.spec.ts` then 😃

**Comment by Spy-Seth** [comment]
I hope this is fine now xD

**Comment by idiotWu** [comment]
[v2.1.1](https://github.com/service-mocker/service-mocker/releases/tag/v2.1.1) is out 🎉

**Comment by Spy-Seth** [comment]
🎉

**Pull request merged**
