### PR TITLE
(doc) update to docute@3.4.5

### PR DESCRIPTION
**Pull request by egoist**
- docute@3.4.5
- use jsdelivr.net instead of unpkg.com

### CODE REVIEW

**Comment by idiotWu** [comment]
Thanks for the PR!

We have been using the old version of docute for so long because I overrode lots of styles in the old version (lazy, in fact 😂).

I'll check this PR later, thanks.

**Comment by idiotWu** [comment]
@egoist omg there're all centered!

I prefer the old layout (at lease on large screens):
screenshot-1
screenshot-2

Noticed the main scrollbar? In the new layout, users could only scroll at the central contents, but they can scroll at everywhere in the old layout.

**Comment by egoist** [comment]
> they can scroll at everywhere in the old layout

Makes sense, I thought centered content is easier to read though 😅 If you don't want this, I can close this PR.

**Comment by idiotWu** [comment]
<del>Or tweaking some css...</del>

Oh I think it's hard to restore the old layout by just tweaking css, some UI-related components must be modified too 😔 (e.g. the scrolling listener).

**Comment by idiotWu** [comment]
Closed as I think we may not upgrade to docute@3 in short term 😅

**Pull request closed without merging**
