### PR TITLE
Avoid decoding empty parameters

### PR DESCRIPTION
**Pull request by idiotWu**
## Description

Solves #37 

## Types of changes

- [x] Bug fix
- [ ] New feature

**If fixing bugs:**

- [x] Tests for the changes have been added.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

CC @caesarsol @VincentBel

### CODE REVIEW

**Comment by caesarsol** [comment]
Damn, you are fast 😄  Looks perfect!

Out of curiosity, what is the `|| value.length === 0` for?

**Comment by idiotWu** [comment]
@caesarsol no idea. Just copied from [express](https://github.com/expressjs/express/blob/master/lib/router/layer.js#L167-L169) 🙃

**Comment by caesarsol** [comment]
Ahahaha seems legit 👍

**Comment by VincentBel** [comment]
@idiotWu I'm wondering when `regex.exec` will result with an empty string 😢

**Comment by idiotWu** [comment]
@VincentBel when group capturing is not optional. For example, "/".match(/\/(\w*)/).

**Comment by VincentBel** [comment]
@idiotWu Got it, merge it now.

**Comment by VincentBel** [comment]
[v2.0.1](https://github.com/service-mocker/service-mocker/releases/tag/v2.0.1) released 🎉 .

**Pull request merged**
